// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, SmartBucket, SmartMemory, SmartSql, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  ADMIN_FRONTEND_URL: string;
  ADMIN_WORKOS_REDIRECT_URI: string;
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  CEREBRAS_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  logger: Logger;
  mem: KvCache;
  REHEARSE_DB: SqlDatabase;
  REHEARSE_SMART_BUCKETS: SmartBucket;
  REHEARSE_SMART_MEMORY: SmartMemory;
  REHEARSE_SMART_SQL: SmartSql;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  tracer: Tracer;
  WORKOS_API_KEY: string;
  WORKOS_CLIENT_ID: string;
  WORKOS_REDIRECT_URI: string;
}
